# Pandas Data Access and Indexing Practice

This notebook explores how to access and modify data in a pandas DataFrame using:

- Column selection
- Row selection

1 `.loc[]`
2 `.iloc[]`
3 `.at[]`
4 `.iat[]`

Slicing rows and columns

The dataset represents employees with information such as name, city, gender, salary, occupation, age, and Python score.

In [28]:
## Import Required Library

# First, import pandas which is used for data manipulation

import pandas as pd
import numpy as np

In [29]:
# Create the DataFrame from raw data
data = [
    [101, 'Ada', 'Paris', 'female', '$100,000','data scientist', 41, 88.0],
    [102, 'Ann', 'Toronto', 'female', '$95,000','digital marketer', 28, 79.0],
    [103, 'Chima', 'California', 'male','$120,000','data engineer', 33, 81.0],
    [104, 'Obi', 'Shanghai', 'male', '$85,000','product manager', 34, 80.0],
    [105, 'Stacey', 'Manchester', 'female','$97,000','ui/ux designer', 38, 68.0],
    [106, 'Ola', 'Cairo', '$98,000', 'female','software engineer', 31, 61.0],
    [107, 'Lyon', 'Osaka', '$96,000', 'male','project manager', 37, 84.0]
]

# Define column names
columns = ['ID', 'Name', 'City', 'Gender', 'Salary', 'Occupation', 'Age', 'Py-score']

# Create DataFrame
df = pd.DataFrame(data, columns=columns)

# Display DataFrame
df

,ID,Name,City,Gender,Salary,Occupation,Age,Py-score
0,101,Ada,Paris,female,"$100,000",data scientist,41,88.0
1,102,Ann,Toronto,female,"$95,000",digital marketer,28,79.0
2,103,Chima,California,male,"$120,000",data engineer,33,81.0
3,104,Obi,Shanghai,male,"$85,000",product manager,34,80.0
4,105,Stacey,Manchester,female,"$97,000",ui/ux designer,38,68.0
5,106,Ola,Cairo,"$98,000",female,software engineer,31,61.0
6,107,Lyon,Osaka,"$96,000",male,project manager,37,84.0

## Accessing a Column

Columns in a pandas DataFrame can be accessed similarly to dictionary keys.

Syntax:

df['column_name']

This returns the column as a **pandas Series**.

In [30]:
# Get row with label 0
df.loc[0]

ID                       101
Name                     Ada
City                   Paris
Gender                female
Salary              $100,000
Occupation    data scientist
Age                       41
Py-score                88.0
Name: 0, dtype: object

## Pandas Data Accessors

Pandas provides four main accessors for retrieving data.

### 1. `.loc[]`
Uses **row and column labels**

### 2. `.iloc[]`
Uses **integer positions**

### 3. `.at[]`
Returns a **single value** using labels

### 4. `.iat[]`
Returns a **single value** using integer positions

In [31]:
'''
Difference Between .loc[] and .iloc[]

.loc[] uses the label e.g df.loc[0] 
.iloc[] uses Integer positions e.g iloc[0]

Both can return the same row when labels match positions.

'''
# Access first row using label
df.loc[0]

ID                       101
Name                     Ada
City                   Paris
Gender                female
Salary              $100,000
Occupation    data scientist
Age                       41
Py-score                88.0
Name: 0, dtype: object

In [32]:
# Access first row using integer position

df.iloc[0]

ID                       101
Name                     Ada
City                   Paris
Gender                female
Salary              $100,000
Occupation    data scientist
Age                       41
Py-score                88.0
Name: 0, dtype: object

## Selecting Columns Using Accessors

You can select columns using both `.loc[]` and `.iloc[]`.

### Syntax

Using labels:
df.loc[:, 'City']

Using integer index:
df.iloc[:, 2]

The colon (:) means **select all rows**.

In [33]:
# Using loc
df.loc[:, 'City']

0         Paris
1       Toronto
2    California
3      Shanghai
4    Manchester
5         Cairo
6         Osaka
Name: City, dtype: object

In [34]:
# Using iloc
df.iloc[:, 2]

0         Paris
1       Toronto
2    California
3      Shanghai
4    Manchester
5         Cairo
6         Osaka
Name: City, dtype: object

## Selecting Multiple Rows and Columns

You can combine slicing and lists to retrieve specific sections of the DataFrame.

Example:

- Rows 1 to 5
- Columns Name and City

In [35]:
# Using loc (label-based)

df.loc[1:5, ['Name','City']]

     Name        City
1     Ann     Toronto
2   Chima  California
3     Obi    Shanghai
4  Stacey  Manchester
5     Ola       Cairo

In [36]:
# Using iloc (position-based)

df.iloc[1:6, [1,2]]

     Name        City
1     Ann     Toronto
2   Chima  California
3     Obi    Shanghai
4  Stacey  Manchester
5     Ola       Cairo

Important difference:

`.loc[]`
- slice **end is included**

`.iloc[]`
- slice **end is excluded**

Example:

loc[1:5] → includes row 5  
iloc[1:6] → stops before 6

## Step Slicing with `.iloc[]`

Slicing follows the format:

start : stop : step

Example:

1:6:2

Meaning:

- start at row position 1
- stop before position 6
- skip every second row

In [37]:
# Select every second row between position 1 and 5

df.iloc[1:6:2, 1]

1    Ann
3    Obi
5    Ola
Name: Name, dtype: object

## Alternative Ways to Write Slices

Instead of writing:

df.iloc[1:6:2, 1]

You can also use:

- Python slice()
- NumPy slicing helper
- Pandas IndexSlice

In [38]:
# Using slice()

df.iloc[slice(1,6,2), 1]

1    Ann
3    Obi
5    Ola
Name: Name, dtype: object

In [39]:
# Using NumPy slice helper

df.iloc[np.s_[1:6:2], 1]

1    Ann
3    Obi
5    Ola
Name: Name, dtype: object

In [40]:

# Using Pandas IndexSlice

df.iloc[pd.IndexSlice[1:6:2], 1]

1    Ann
3    Obi
5    Ola
Name: Name, dtype: object

## Accessing a Single Value

When retrieving a single value, pandas recommends using:

- `.at[]` → label-based
- `.iat[]` → integer position

In [41]:
# Using labels

df.at[2, 'Name']

'Chima'

In [42]:
# Using integer positions

df.iat[2,1]

'Chima'

## Modifying Data Using `.loc[]`

`.loc[]` can also be used to modify values in a DataFrame.

In [43]:
# View python score column
df.loc[:, 'Py-score']

0    88.0
1    79.0
2    81.0
3    80.0
4    68.0
5    61.0
6    84.0
Name: Py-score, dtype: float64

In [46]:
# Modify first three rows

df.loc[:2, 'Py-score'] = [50,60,70]
print(df)

    ID    Name        City   Gender    Salary         Occupation  Age  \
0  101     Ada       Paris   female  $100,000     data scientist   41
1  102     Ann     Toronto   female   $95,000   digital marketer   28
2  103   Chima  California     male  $120,000      data engineer   33
3  104     Obi    Shanghai     male   $85,000    product manager   34
4  105  Stacey  Manchester   female   $97,000     ui/ux designer   38
5  106     Ola       Cairo  $98,000    female  software engineer   31
6  107    Lyon       Osaka  $96,000      male    project manager   37

   Py-score
0      50.0
1      60.0
2      70.0
3       0.0
4       0.0
5       0.0
6       0.0

In [47]:
# Set remaining values to 0
df.loc[3:, 'Py-score'] = 0

print(df)

    ID    Name        City   Gender    Salary         Occupation  Age  \
0  101     Ada       Paris   female  $100,000     data scientist   41
1  102     Ann     Toronto   female   $95,000   digital marketer   28
2  103   Chima  California     male  $120,000      data engineer   33
3  104     Obi    Shanghai     male   $85,000    product manager   34
4  105  Stacey  Manchester   female   $97,000     ui/ux designer   38
5  106     Ola       Cairo  $98,000    female  software engineer   31
6  107    Lyon       Osaka  $96,000      male    project manager   37

   Py-score
0      50.0
1      60.0
2      70.0
3       0.0
4       0.0
5       0.0
6       0.0

## Modifying Columns Using `.iloc[]`

Negative indices can be used with `.iloc[]` to access columns from the end.

Example:

-1 refers to the last column.

In [48]:
# Modify last column
df.iloc[:, -1] = np.array([88,79,81,80,68,61,84])

df

,ID,Name,City,Gender,Salary,Occupation,Age,Py-score
0,101,Ada,Paris,female,"$100,000",data scientist,41,88.0
1,102,Ann,Toronto,female,"$95,000",digital marketer,28,79.0
2,103,Chima,California,male,"$120,000",data engineer,33,81.0
3,104,Obi,Shanghai,male,"$85,000",product manager,34,80.0
4,105,Stacey,Manchester,female,"$97,000",ui/ux designer,38,68.0
5,106,Ola,Cairo,"$98,000",female,software engineer,31,61.0
6,107,Lyon,Osaka,"$96,000",male,project manager,37,84.0

## Key Takeaways

1. `.loc[]` works with **labels**
2. `.iloc[]` works with **integer positions**
3. `.loc[]` slicing is **inclusive**
4. `.iloc[]` slicing is **exclusive**
5. `.at[]` and `.iat[]` are optimized for **single value access**