In [19]:
# import the necessary document

import pandas as pd
import numpy as np

In [20]:
# creating a dataframe 

data = [
    [101, 'Ada',    'Paris',      'female', '$100,000', 'data scientist',   41, 88.0],
    [102, 'Ann',    'Toronto',    'female', '$95,000',  'digital marketer', 28, 79.0],
    [103, 'Chima',  'California', 'male',   '$120,000', 'data engineer',    33, 81.0],
    [104, 'Obi',    'Shanghai',   'male',   '$85,000',  'product manager',  34, 80.0],
    [105, 'Stacey', 'Manchester', 'female', '$97,000',  'ui/ux designer',   38, 68.0],
    [106, 'Ola',    'Cairo',      'female', '$98,000',  'software engineer',31, 61.0], 
    [107, 'Lyon',   'Osaka',      'male',   '$96,000',  'project manager',  37, 84.0],  
]

columns = ['ID', 'Name', 'City', 'Gender', 'Salary', 'Occupation', 'Age', 'Py-score']
df = pd.DataFrame(data, columns=columns)

In [21]:
''' 
we are going to insert new column using diff method

'''

df['AWS-score'] = np.array([71.0, 95.0, 88.0, 79.0, 91.0, 91.0, 75.0])

df

,ID,Name,City,Gender,Salary,Occupation,Age,Py-score,AWS-score
0,101,Ada,Paris,female,"$100,000",data scientist,41,88.0,71.0
1,102,Ann,Toronto,female,"$95,000",digital marketer,28,79.0,95.0
2,103,Chima,California,male,"$120,000",data engineer,33,81.0,88.0
3,104,Obi,Shanghai,male,"$85,000",product manager,34,80.0,79.0
4,105,Stacey,Manchester,female,"$97,000",ui/ux designer,38,68.0,91.0
5,106,Ola,Cairo,female,"$98,000",software engineer,31,61.0,91.0
6,107,Lyon,Osaka,male,"$96,000",project manager,37,84.0,75.0

In [22]:
# adding a new column GCP-score with the .insert() method, using loc to identify the particular location in our datafarme

df.insert(loc= 5, column = 'GCP-score',
          value=np.array([80.0, 83.0, 78.0, 88.0, 75.0, 72.0, 81.0]))
df

,ID,Name,City,Gender,Salary,GCP-score,Occupation,Age,Py-score,AWS-score
0,101,Ada,Paris,female,"$100,000",80.0,data scientist,41,88.0,71.0
1,102,Ann,Toronto,female,"$95,000",83.0,digital marketer,28,79.0,95.0
2,103,Chima,California,male,"$120,000",78.0,data engineer,33,81.0,88.0
3,104,Obi,Shanghai,male,"$85,000",88.0,product manager,34,80.0,79.0
4,105,Stacey,Manchester,female,"$97,000",75.0,ui/ux designer,38,68.0,91.0
5,106,Ola,Cairo,female,"$98,000",72.0,software engineer,31,61.0,91.0
6,107,Lyon,Osaka,male,"$96,000",81.0,project manager,37,84.0,75.0

In [23]:
# adding a column at the end in your DataFrame directily without specify the location and a particular values

df['Bech-mark'] = 60.0
df

,ID,Name,City,Gender,Salary,GCP-score,Occupation,Age,Py-score,AWS-score,Bech-mark
0,101,Ada,Paris,female,"$100,000",80.0,data scientist,41,88.0,71.0,60.0
1,102,Ann,Toronto,female,"$95,000",83.0,digital marketer,28,79.0,95.0,60.0
2,103,Chima,California,male,"$120,000",78.0,data engineer,33,81.0,88.0,60.0
3,104,Obi,Shanghai,male,"$85,000",88.0,product manager,34,80.0,79.0,60.0
4,105,Stacey,Manchester,female,"$97,000",75.0,ui/ux designer,38,68.0,91.0,60.0
5,106,Ola,Cairo,female,"$98,000",72.0,software engineer,31,61.0,91.0,60.0
6,107,Lyon,Osaka,male,"$96,000",81.0,project manager,37,84.0,75.0,60.0

In [24]:
'''
we can perfom basic arithemetics in our DF using our labels or column in our Dataframe

'''

df['Total score']= df['GCP-score'] + df['AWS-score']
print('Total score:')
print(df['Total score'])

Total score:
0    151.0
1    178.0
2    166.0
3    167.0
4    166.0
5    163.0
6    156.0
Name: Total score, dtype: float64

In [25]:
df['Py-score'] / df['Bech-mark']
print('Answer')
print(df['Py-score'])

Answer
0    88.0
1    79.0
2    81.0
3    80.0
4    68.0
5    61.0
6    84.0
Name: Py-score, dtype: float64

In [26]:
# we can use the basic arithemetics to add new column 

df['Total'] =\
0.4 * df['Py-score'] + 0.3 * df['GCP-score'] + 0.3 * df['AWS-score']

print('Newscore added')
print(df['Total'])

Newscore added
0    80.5
1    85.0
2    82.2
3    82.1
4    77.0
5    73.3
6    80.4
Name: Total, dtype: float64

In [27]:
df

,ID,Name,City,Gender,Salary,GCP-score,Occupation,Age,Py-score,AWS-score,Bech-mark,Total score,Total
0,101,Ada,Paris,female,"$100,000",80.0,data scientist,41,88.0,71.0,60.0,151.0,80.5
1,102,Ann,Toronto,female,"$95,000",83.0,digital marketer,28,79.0,95.0,60.0,178.0,85.0
2,103,Chima,California,male,"$120,000",78.0,data engineer,33,81.0,88.0,60.0,166.0,82.2
3,104,Obi,Shanghai,male,"$85,000",88.0,product manager,34,80.0,79.0,60.0,167.0,82.1
4,105,Stacey,Manchester,female,"$97,000",75.0,ui/ux designer,38,68.0,91.0,60.0,166.0,77.0
5,106,Ola,Cairo,female,"$98,000",72.0,software engineer,31,61.0,91.0,60.0,163.0,73.3
6,107,Lyon,Osaka,male,"$96,000",81.0,project manager,37,84.0,75.0,60.0,156.0,80.4

In [28]:
score = df.iloc[:, 2:5]
score

         City  Gender    Salary
0       Paris  female  $100,000
1     Toronto  female   $95,000
2  California    male  $120,000
3    Shanghai    male   $85,000
4  Manchester  female   $97,000
5       Cairo  female   $98,000
6       Osaka    male   $96,000

In [29]:
df.drop(labels='Total', axis=0, inplace =True)

KeyError: "['Total'] not found in axis"

In [ ]:
df