# Determining Data Statistics
pandas provides many statistical methods for DataFrames. You can get basic statistics for the numerical columns of a pandas DataFrame with .describe():

In [2]:
# To get the summary of our DataFrame we use .describe() but first let start by creating our dataset

import pandas as pd
import numpy as np

# creating a dataframe 

data = [
    [101, 'Ada',    'Paris',      'female', '$100,000', 'data scientist',   41, 88.0],
    [102, 'Ann',    'Toronto',    'female', '$95,000',  'digital marketer', 28, 79.0],
    [103, 'Chima',  'California', 'male',   '$120,000', 'data engineer',    33, 81.0],
    [104, 'Obi',    'Shanghai',   'male',   '$85,000',  'product manager',  34, 80.0],
    [105, 'Stacey', 'Manchester', 'female', '$97,000',  'ui/ux designer',   38, 68.0],
    [106, 'Ola',    'Cairo',      'female', '$98,000',  'software engineer',31, 61.0], 
    [107, 'Lyon',   'Osaka',      'male',   '$96,000',  'project manager',  37, 84.0],  
]

columns = ['ID', 'Name', 'City', 'Gender', 'Salary', 'Occupation', 'Age', 'Py-score']
df = pd.DataFrame(data, columns=columns)

In [5]:
# to get the summary statistics like count, mean, std, min, etc of our dataframe

df.describe()

               ID        Age   Py-score
count    7.000000   7.000000   7.000000
mean   104.000000  34.571429  77.285714
std      2.160247   4.429339   9.446592
min    101.000000  28.000000  61.000000
25%    102.500000  32.000000  73.500000
50%    104.000000  34.000000  80.000000
75%    105.500000  37.500000  82.500000
max    107.000000  41.000000  88.000000

In [11]:
# Recreating my DF and cleaning my salary column from str to float dtype

data = [
    [101, 'Ada',    'Paris',      'female', '$100,000', 'data scientist',   41, 88.0],
    [102, 'Ann',    'Toronto',    'female', '$95,000',  'digital marketer', 28, 79.0],
    [103, 'Chima',  'California', 'male',   '$120,000', 'data engineer',    33, 81.0],
    [104, 'Obi',    'Shanghai',   'male',   '$85,000',  'product manager',  34, 80.0],
    [105, 'Stacey', 'Manchester', 'female', '$97,000',  'ui/ux designer',   38, 68.0],
    [106, 'Ola',    'Cairo',      'female', '$98,000',  'software engineer',31, 61.0], 
    [107, 'Lyon',   'Osaka',      'male',   '$96,000',  'project manager',  37, 84.0],  
]
columns = ['ID', 'Name', 'City', 'Gender', 'Salary', 'Occupation', 'Age', 'Py-score']
df = pd.DataFrame(data, columns=columns)

# Clean the Salary column — remove $ and , then convert to integer
df['Salary'] = df['Salary'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(int)

# Now describe() will include all numeric columns
df.describe()

               ID         Salary        Age   Py-score
count    7.000000       7.000000   7.000000   7.000000
mean   104.000000   98714.285714  34.571429  77.285714
std      2.160247   10546.947200   4.429339   9.446592
min    101.000000   85000.000000  28.000000  61.000000
25%    102.500000   95500.000000  32.000000  73.500000
50%    104.000000   97000.000000  34.000000  80.000000
75%    105.500000   99000.000000  37.500000  82.500000
max    107.000000  120000.000000  41.000000  88.000000

In [14]:
df.mean(numeric_only = True)

ID            104.000000
Salary      98714.285714
Age            34.571429
Py-score       77.285714
dtype: float64

In [15]:
df.std(numeric_only =True)

ID              2.160247
Salary      10546.947200
Age             4.429339
Py-score        9.446592
dtype: float64