# Filtering Data
Data filtering is another powerful feature of pandas. It works similarly to indexing with Boolean arrays in NumPy.

If you apply some logical operation on a Series object, then you’ll get another Series with the Boolean values True and False:

In [4]:
import pandas as pd
import numpy as np

# create our dataframe and data into it


data = [
    [101, 'Ada',    'Paris',      'female', '$100,000', 'data scientist',   41, 88.0],
    [102, 'Ann',    'Toronto',    'female', '$95,000',  'digital marketer', 28, 79.0],
    [103, 'Chima',  'California', 'male',   '$120,000', 'data engineer',    33, 81.0],
    [104, 'Obi',    'Shanghai',   'male',   '$85,000',  'product manager',  34, 80.0],
    [105, 'Stacey', 'Manchester', 'female', '$97,000',  'ui/ux designer',   38, 68.0],
    [106, 'Ola',    'Cairo',      'female', '$98,000',  'software engineer',31, 61.0], 
    [107, 'Lyon',   'Osaka',      'male',   '$96,000',  'project manager',  37, 84.0],  
]

columns = ['ID', 'Name', 'City', 'Gender', 'Salary', 'Occupation', 'Age', 'Py-score']
df = pd.DataFrame(data, columns=columns)

# adding a new column GCP-score with the .insert() method, using loc to identify the particular location in our datafarme

df.insert(loc= 5, column = 'GCP-score',
          value=np.array([80.0, 83.0, 78.0, 88.0, 75.0, 72.0, 81.0]))
df

,ID,Name,City,Gender,Salary,GCP-score,Occupation,Age,Py-score
0,101,Ada,Paris,female,"$100,000",80.0,data scientist,41,88.0
1,102,Ann,Toronto,female,"$95,000",83.0,digital marketer,28,79.0
2,103,Chima,California,male,"$120,000",78.0,data engineer,33,81.0
3,104,Obi,Shanghai,male,"$85,000",88.0,product manager,34,80.0
4,105,Stacey,Manchester,female,"$97,000",75.0,ui/ux designer,38,68.0
5,106,Ola,Cairo,female,"$98,000",72.0,software engineer,31,61.0
6,107,Lyon,Osaka,male,"$96,000",81.0,project manager,37,84.0

In [9]:
'''
lets filter our dataset with usng this GCP-score column to know which row is >= 80, 
True means >= 80 while false mean less than 80
'''

f = df['GCP-score']>= 80
f

0     True
1     True
2    False
3     True
4    False
5    False
6     True
Name: GCP-score, dtype: bool

In [10]:
'''
If we want to see all our table or dataframe,
The expression df[f] returns a pandas DataFrame with the rows from df that correspond to True in filter_:

'''

df[f]

,ID,Name,City,Gender,Salary,GCP-score,Occupation,Age,Py-score
0,101,Ada,Paris,female,"$100,000",80.0,data scientist,41,88.0
1,102,Ann,Toronto,female,"$95,000",83.0,digital marketer,28,79.0
3,104,Obi,Shanghai,male,"$85,000",88.0,product manager,34,80.0
6,107,Lyon,Osaka,male,"$96,000",81.0,project manager,37,84.0

You can create very powerful and sophisticated expressions by combining logical operations with the following operators:

#### NOT (~)
#### AND (&)
#### OR (|)
#### XOR (^)

In [15]:
'''
For example, you can get a DataFrame with the candidates whose GCP-score and Py-score 
are greater than or equal to 80:

'''

df[(df['GCP-score'] >=80) & (df['Py-score'] >=80)]

,ID,Name,City,Gender,Salary,GCP-score,Occupation,Age,Py-score
0,101,Ada,Paris,female,"$100,000",80.0,data scientist,41,88.0
3,104,Obi,Shanghai,male,"$85,000",88.0,product manager,34,80.0
6,107,Lyon,Osaka,male,"$96,000",81.0,project manager,37,84.0

In [23]:
df[(df['GCP-score'] >=80) & (df['Age'] <=35)]

,ID,Name,City,Gender,Salary,GCP-score,Occupation,Age,Py-score
1,102,Ann,Toronto,female,"$95,000",83.0,digital marketer,28,79.0
3,104,Obi,Shanghai,male,"$85,000",88.0,product manager,34,80.0

In [17]:
'''
For some operations that require data filtering, it’s more convenient to use .where(). 
It replaces the values in the positions where the provided condition isn’t satisfied:

'''

df['Py-score'].where(cond=df['Py-score'] >= 80, other=0.0)

0    88.0
1     0.0
2    81.0
3    80.0
4     0.0
5     0.0
6    84.0
Name: Py-score, dtype: float64