# Handling Missing Data

Missing data is very common in dataset pandas usually represents missing data with NaN (not a number) values. In Python, you can get NaN with float('nan'), math.nan, or numpy.nan. Starting with pandas 1.0, newer types like BooleanDtype, Int8Dtype, Int16Dtype, Int32Dtype, and Int64Dtype use pandas.NA as a missing value.

In [4]:
# an example or illustration of a pandas DataFrame with a missing value:
import pandas as pd
import numpy as np

'''
This is an exmaple of missing dataset in a real word secenario The variable df_ refers to the DataFrame with one column, x,
and seven values. The third value is nan and is considered missing by default.
'''

df = pd.DataFrame({'x': [1, 2, np.nan, 4, np.nan, 6, np.nan, 7]})
df

     x
0  1.0
1  2.0
2  NaN
3  4.0
4  NaN
5  6.0
6  NaN
7  7.0

In [5]:
'''
Calculating With Missing Data

Many pandas methods omit nan values when performing calculations unless they are explicitly instructed not to
uisng the .mean(skipna=False):

'''
# this will skip the NaN value
df.mean()

x    4.0
dtype: float64

In [6]:
df.mean(skipna=False)

x   NaN
dtype: float64

## Filling Missing Data
pandas has several options for filling, or replacing, missing values with other values. One of the most convenient methods is .fillna(). You can use it to replace missing values with:

* Specified values
* The values above the missing value
* The values below the missing value

In [9]:
# we can apply all the option above to fill the missing value
#  .fillna() .fillna(value=0) replaces the missing value with 0.0, which you specified with value

df.fillna(value=0)

     x
0  1.0
1  2.0
2  0.0
3  4.0
4  0.0
5  6.0
6  0.0
7  7.0

In [10]:
# .fillna(method='ffill') replaces the missing value with the value above it, which is 2.0. In the third example

df.fillna(method='ffill')

C:\Users\HP\AppData\Local\Temp\ipykernel_6448\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     x
0  1.0
1  2.0
2  2.0
3  4.0
4  4.0
5  6.0
6  6.0
7  7.0

In [12]:
# .fillna(method='bfill') uses the value below the missing value, which is 4.0.

df.fillna(method='bfill')

C:\Users\HP\AppData\Local\Temp\ipykernel_6448\1757386327.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

     x
0  1.0
1  2.0
2  4.0
3  4.0
4  6.0
5  6.0
6  7.0
7  7.0

In [14]:


df.dropna()

     x
0  1.0
1  2.0
3  4.0
5  6.0
7  7.0

In [15]:
for col_label, col in df.iteritems():
    print(col_label, col, sep='\n', end='\n\n')

AttributeError: 'DataFrame' object has no attribute 'iteritems'