In [2]:
# First, import pandas which is used for data manipulation

import pandas as pd
import numpy as np

In [3]:
# Create the DataFrame from raw data
data = [
    [101, 'Ada', 'Paris', 'female', '$100,000','data scientist', 41, 88.0],
    [102, 'Ann', 'Toronto', 'female', '$95,000','digital marketer', 28, 79.0],
    [103, 'Chima', 'California', 'male','$120,000','data engineer', 33, 81.0],
    [104, 'Obi', 'Shanghai', 'male', '$85,000','product manager', 34, 80.0],
    [105, 'Stacey', 'Manchester', 'female','$97,000','ui/ux designer', 38, 68.0],
    [106, 'Ola', 'Cairo', '$98,000', 'female','software engineer', 31, 61.0],
    [107, 'Lyon', 'Osaka', '$96,000', 'male','project manager', 37, 84.0]
]

# Define column names
columns = ['ID', 'Name', 'City', 'Gender', 'Salary', 'Occupation', 'Age', 'Py-score']

# Create DataFrame
df = pd.DataFrame(data, columns=columns)

# Display DataFrame
df

,ID,Name,City,Gender,Salary,Occupation,Age,Py-score
0,101,Ada,Paris,female,"$100,000",data scientist,41,88.0
1,102,Ann,Toronto,female,"$95,000",digital marketer,28,79.0
2,103,Chima,California,male,"$120,000",data engineer,33,81.0
3,104,Obi,Shanghai,male,"$85,000",product manager,34,80.0
4,105,Stacey,Manchester,female,"$97,000",ui/ux designer,38,68.0
5,106,Ola,Cairo,"$98,000",female,software engineer,31,61.0
6,107,Lyon,Osaka,"$96,000",male,project manager,37,84.0

In [4]:
# To insert a da

urch = pd.Series(
    data=[108, "Urch", "Lagos", "male", "$75,000", "Automech", 37, 83.0],
    index=df.columns,
    name=108
)

df

,ID,Name,City,Gender,Salary,Occupation,Age,Py-score
0,101,Ada,Paris,female,"$100,000",data scientist,41,88.0
1,102,Ann,Toronto,female,"$95,000",digital marketer,28,79.0
2,103,Chima,California,male,"$120,000",data engineer,33,81.0
3,104,Obi,Shanghai,male,"$85,000",product manager,34,80.0
4,105,Stacey,Manchester,female,"$97,000",ui/ux designer,38,68.0
5,106,Ola,Cairo,"$98,000",female,software engineer,31,61.0
6,107,Lyon,Osaka,"$96,000",male,project manager,37,84.0

In [5]:
# Create the new row as a Series
urch = pd.Series(
    data=[108, "Urch", "Lagos", "male", "$75,000", "Automech", 37, 83.0],
    index=df.columns,
    name=108
)

# Use pd.concat() instead of append
df = pd.concat([df, urch.to_frame().T])

# Display the DataFrame
df

,ID,Name,City,Gender,Salary,Occupation,Age,Py-score
0,101,Ada,Paris,female,"$100,000",data scientist,41,88.0
1,102,Ann,Toronto,female,"$95,000",digital marketer,28,79.0
2,103,Chima,California,male,"$120,000",data engineer,33,81.0
3,104,Obi,Shanghai,male,"$85,000",product manager,34,80.0
4,105,Stacey,Manchester,female,"$97,000",ui/ux designer,38,68.0
5,106,Ola,Cairo,"$98,000",female,software engineer,31,61.0
6,107,Lyon,Osaka,"$96,000",male,project manager,37,84.0
108,108,Urch,Lagos,male,"$75,000",Automech,37,83.0

In [6]:
df.drop (108)

    ID    Name        City   Gender    Salary         Occupation Age Py-score
0  101     Ada       Paris   female  $100,000     data scientist  41     88.0
1  102     Ann     Toronto   female   $95,000   digital marketer  28     79.0
2  103   Chima  California     male  $120,000      data engineer  33     81.0
3  104     Obi    Shanghai     male   $85,000    product manager  34     80.0
4  105  Stacey  Manchester   female   $97,000     ui/ux designer  38     68.0
5  106     Ola       Cairo  $98,000    female  software engineer  31     61.0
6  107    Lyon       Osaka  $96,000      male    project manager  37     84.0

In [7]:
data = [
    [101, 'Ada',    'Paris',      'female', '$100,000', 'data scientist',   41, 88.0],
    [102, 'Ann',    'Toronto',    'female', '$95,000',  'digital marketer', 28, 79.0],
    [103, 'Chima',  'California', 'male',   '$120,000', 'data engineer',    33, 81.0],
    [104, 'Obi',    'Shanghai',   'male',   '$85,000',  'product manager',  34, 80.0],
    [105, 'Stacey', 'Manchester', 'female', '$97,000',  'ui/ux designer',   38, 68.0],
    [106, 'Ola',    'Cairo',      'female', '$98,000',  'software engineer',31, 61.0],  # ✅ fixed
    [107, 'Lyon',   'Osaka',      'male',   '$96,000',  'project manager',  37, 84.0],  # ✅ fixed
]

columns = ['ID', 'Name', 'City', 'Gender', 'Salary', 'Occupation', 'Age', 'Py-score']
df = pd.DataFrame(data, columns=columns)

In [8]:
# Now this works — 7 values for 7 rows 

df['AWS-score'] = np.array([71.0, 95.0, 88.0, 79.0, 91.0, 91.0, 80.0])

In [9]:
df

,ID,Name,City,Gender,Salary,Occupation,Age,Py-score,AWS-score
0,101,Ada,Paris,female,"$100,000",data scientist,41,88.0,71.0
1,102,Ann,Toronto,female,"$95,000",digital marketer,28,79.0,95.0
2,103,Chima,California,male,"$120,000",data engineer,33,81.0,88.0
3,104,Obi,Shanghai,male,"$85,000",product manager,34,80.0,79.0
4,105,Stacey,Manchester,female,"$97,000",ui/ux designer,38,68.0,91.0
5,106,Ola,Cairo,female,"$98,000",software engineer,31,61.0,91.0
6,107,Lyon,Osaka,male,"$96,000",project manager,37,84.0,80.0

In [10]:
# You can add a new column with a single value:

df["Toal_mark"] = 0.0
df

,ID,Name,City,Gender,Salary,Occupation,Age,Py-score,AWS-score,Toal_mark
0,101,Ada,Paris,female,"$100,000",data scientist,41,88.0,71.0,0.0
1,102,Ann,Toronto,female,"$95,000",digital marketer,28,79.0,95.0,0.0
2,103,Chima,California,male,"$120,000",data engineer,33,81.0,88.0,0.0
3,104,Obi,Shanghai,male,"$85,000",product manager,34,80.0,79.0,0.0
4,105,Stacey,Manchester,female,"$97,000",ui/ux designer,38,68.0,91.0,0.0
5,106,Ola,Cairo,female,"$98,000",software engineer,31,61.0,91.0,0.0
6,107,Lyon,Osaka,male,"$96,000",project manager,37,84.0,80.0,0.0

In [11]:
''' The last code didn't specify the location we can add column to our dataframe 
to specify the location of the new column. 
If the location of the new column is important, then you can use .insert()  instead:
'''
df.insert(loc=4, column='js_score', 
          value=np.array([86.0, 81.0, 78.0, 88.0, 74.0, 70.0, 81.0]))
df

,ID,Name,City,Gender,js_score,Salary,Occupation,Age,Py-score,AWS-score,Toal_mark
0,101,Ada,Paris,female,86.0,"$100,000",data scientist,41,88.0,71.0,0.0
1,102,Ann,Toronto,female,81.0,"$95,000",digital marketer,28,79.0,95.0,0.0
2,103,Chima,California,male,78.0,"$120,000",data engineer,33,81.0,88.0,0.0
3,104,Obi,Shanghai,male,88.0,"$85,000",product manager,34,80.0,79.0,0.0
4,105,Stacey,Manchester,female,74.0,"$97,000",ui/ux designer,38,68.0,91.0,0.0
5,106,Ola,Cairo,female,70.0,"$98,000",software engineer,31,61.0,91.0,0.0
6,107,Lyon,Osaka,male,81.0,"$96,000",project manager,37,84.0,80.0,0.0

In [13]:
# To delete one or more column in your dataframe use the del df statement : del df['col']

del df['Toal_mark']
df

,ID,Name,City,Gender,js_score,Salary,Occupation,Age,Py-score,AWS-score
0,101,Ada,Paris,female,86.0,"$100,000",data scientist,41,88.0,71.0
1,102,Ann,Toronto,female,81.0,"$95,000",digital marketer,28,79.0,95.0
2,103,Chima,California,male,78.0,"$120,000",data engineer,33,81.0,88.0
3,104,Obi,Shanghai,male,88.0,"$85,000",product manager,34,80.0,79.0
4,105,Stacey,Manchester,female,74.0,"$97,000",ui/ux designer,38,68.0,91.0
5,106,Ola,Cairo,female,70.0,"$98,000",software engineer,31,61.0,91.0
6,107,Lyon,Osaka,male,81.0,"$96,000",project manager,37,84.0,80.0

In [15]:
# add a new column to your dataframe with the specified value
df["Total_mark"] = 0.0
df

,ID,Name,City,Gender,js_score,Salary,Occupation,Age,Py-score,AWS-score,Total_mark
0,101,Ada,Paris,female,86.0,"$100,000",data scientist,41,88.0,71.0,0.0
1,102,Ann,Toronto,female,81.0,"$95,000",digital marketer,28,79.0,95.0,0.0
2,103,Chima,California,male,78.0,"$120,000",data engineer,33,81.0,88.0,0.0
3,104,Obi,Shanghai,male,88.0,"$85,000",product manager,34,80.0,79.0,0.0
4,105,Stacey,Manchester,female,74.0,"$97,000",ui/ux designer,38,68.0,91.0,0.0
5,106,Ola,Cairo,female,70.0,"$98,000",software engineer,31,61.0,91.0,0.0
6,107,Lyon,Osaka,male,81.0,"$96,000",project manager,37,84.0,80.0,0.0

In [17]:
# Another way to remove a column or delete a column is to use .pop()

df.pop('Total_mark')
df

,ID,Name,City,Gender,js_score,Salary,Occupation,Age,Py-score,AWS-score
0,101,Ada,Paris,female,86.0,"$100,000",data scientist,41,88.0,71.0
1,102,Ann,Toronto,female,81.0,"$95,000",digital marketer,28,79.0,95.0
2,103,Chima,California,male,78.0,"$120,000",data engineer,33,81.0,88.0
3,104,Obi,Shanghai,male,88.0,"$85,000",product manager,34,80.0,79.0
4,105,Stacey,Manchester,female,74.0,"$97,000",ui/ux designer,38,68.0,91.0
5,106,Ola,Cairo,female,70.0,"$98,000",software engineer,31,61.0,91.0
6,107,Lyon,Osaka,male,81.0,"$96,000",project manager,37,84.0,80.0

In [22]:
''' you can also delete or remove a column using .drop() ,
but you need to specific the colun name using labels and axis as column, while inplace to make the changes 

'''

df.drop(labels='AWS-score', axis=1, inplace =True)
df

,ID,Name,City,Gender,js_score,Salary,Occupation,Age,Py-score
0,101,Ada,Paris,female,86.0,"$100,000",data scientist,41,88.0
1,102,Ann,Toronto,female,81.0,"$95,000",digital marketer,28,79.0
2,103,Chima,California,male,78.0,"$120,000",data engineer,33,81.0
3,104,Obi,Shanghai,male,88.0,"$85,000",product manager,34,80.0
4,105,Stacey,Manchester,female,74.0,"$97,000",ui/ux designer,38,68.0
5,106,Ola,Cairo,female,70.0,"$98,000",software engineer,31,61.0
6,107,Lyon,Osaka,male,81.0,"$96,000",project manager,37,84.0