In [134]:
# import pandas
# import numpy

import pandas as pd
import numpy as np

data = {
     'name': ['Ada', 'Chima', 'Obi', 'Lyon', 'Stacy','Ola', 'Ann'],
     'city': ['Paris', 'Lagos', 'Owerri', 'Shanghai','Manchester', 'Abuja', 'Osaka'],
     'age': [41, 28, 33, 34, 38, 31, 37],
     'py-score': [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
      
}

row_labels = [101, 102, 103, 104, 105, 106, 107]

# Create a pandas dataframe

df = pd.DataFrame(data=data, index = row_labels)

# Display the DataFrame

print("\n Our First DataFrame:\n",df)

 Our First DataFrame:
       name        city  age  py-score
101    Ada       Paris   41      88.0
102  Chima       Lagos   28      79.0
103    Obi      Owerri   33      81.0
104   Lyon    Shanghai   34      80.0
105  Stacy  Manchester   38      68.0
106    Ola       Abuja   31      61.0
107    Ann       Osaka   37      84.0

In [135]:
# To Display the first n row use df.head() 
# To Display the last n row use df.tail() 

print("\nDisplay the first two row:\n",df.head(2))


print("\nDisplay the last two row:\n",df.tail(2))

Display the first two row:
       name   city  age  py-score
101    Ada  Paris   41      88.0
102  Chima  Lagos   28      79.0

Display the last two row:
     name   city  age  py-score
106  Ola  Abuja   31      61.0
107  Ann  Osaka   37      84.0

In [136]:
'''
you can access a column in your dataframe the same way you would get a value from a dictionary: 
cities = df['city']. 
but the most convienent way is if a string that is a valid Python identifier, 
hen you can use dot notation to access it df.age

'''
# show different two column using the two types discuss

name = df['name']

df['name']
df.city

101         Paris
102         Lagos
103        Owerri
104      Shanghai
105    Manchester
106         Abuja
107         Osaka
Name: city, dtype: object

# Creating a Pandas DataFrame Using A Dictionary

In [137]:
# Creating a DF with Dict

data = {
    'Student': ['Ada', 'Chima', 'Obi', 'Lyon', 'Stacy'],
    'rank' :np.array([1, 4, 3, 5, 2]), 
    'Mark': 100
}


row_labels = [101, 102, 103, 104, 105,]

df = pd.DataFrame(data=data, index=row_labels)

# Display the dataframe

print(df)

    Student  rank  Mark
101     Ada     1   100
102   Chima     4   100
103     Obi     3   100
104    Lyon     5   100
105   Stacy     2   100

# Creating a pandas DataFrame With Lists

In [138]:


data = [
    {'Student': 'Ada', 'rank' : 1, 'Mark': 100},
    {'Student': 'Chima', 'rank' : 2, 'Mark': 100},
    {'Student': 'Obi', 'rank' : 3, 'Mark': 100},
    {'Student': 'Lyon', 'rank' : 4, 'Mark': 100},
    {'Student': 'Stacy', 'rank' : 5, 'Mark': 100}
]

row_labels = [101, 102, 103, 104, 105,]

df = pd.DataFrame(data=data, index=row_labels)

df

    Student  rank  Mark
101     Ada     1   100
102   Chima     2   100
103     Obi     3   100
104    Lyon     4   100
105   Stacy     5   100

In [139]:
# dataset
data = [
    {'Student': 'Ada', 'rank' : 1, 'Mark': 100},
    {'Student': 'Chima', 'rank' : 2, 'Mark': 100},
    {'Student': 'Obi', 'rank' : 3, 'Mark': 100},
    {'Student': 'Lyon', 'rank' : 4, 'Mark': 100},
    {'Student': 'Stacy', 'rank' : 5, 'Mark': 100}
]

# Create the nested list 'l' using list comprehension
l = [[item['Student'], item['rank'], item['Mark']] for item in data]

# Display the nested list
print("Nested List (l):", l)

# Create the DataFrame using the nested list
df = pd.DataFrame(l, columns=['Student', 'rank', 'Mark'])

print("\nDataFrame from nested list:\n", df)

Nested List (l): [['Ada', 1, 100], ['Chima', 2, 100], ['Obi', 3, 100], ['Lyon', 4, 100], ['Stacy', 5, 100]]

DataFrame from nested list:
   Student  rank  Mark
0     Ada     1   100
1   Chima     2   100
2     Obi     3   100
3    Lyon     4   100
4   Stacy     5   100

# Creating a pandas DataFrame With NumPy Arrays

In [140]:
# Extract each values from our dictionary 

arr = np.array([
    [d["Student"], d["rank"], d["Mark"]]
    for d in data
])

In [141]:
#View array we just extracted
arr

array([['Ada', '1', '100'],
       ['Chima', '2', '100'],
       ['Obi', '3', '100'],
       ['Lyon', '4', '100'],
       ['Stacy', '5', '100']], dtype='<U21')

In [142]:
# converting it back to a dataframe

df = pd.DataFrame(arr, columns=["Student", "Rank", "Mark"])

df

  Student Rank Mark
0     Ada    1  100
1   Chima    2  100
2     Obi    3  100
3    Lyon    4  100
4   Stacy    5  100

In [143]:
# splitting the data type to get only the numeric data

arr = np.array([
    [d["rank"], d["Mark"]]
    for d in data
])

arr

array([[  1, 100],
       [  2, 100],
       [  3, 100],
       [  4, 100],
       [  5, 100]])

In [144]:
df = pd.DataFrame(arr,columns=["rank","Mark"])

df["Student"] = [d["Student"] for d in data]

df

   rank  Mark Student
0     1   100     Ada
1     2   100   Chima
2     3   100     Obi
3     4   100    Lyon
4     5   100   Stacy

# Creating a pandas DataFrame From Files

In [145]:
'''
You can save and load the data and labels from a pandas DataFrame to and from a number of file types, 
including CSV, Excel, SQL, JSON, and more. This is a very powerful feature.
'''

# Save this raw data as a csv file using to_csv()

# Create the DataFrame from the raw data
data = [
    [101, 'Ada', 'Paris', 'female', '$100,000','data scientist', 41, 88.0,],
    [102, 'Ann', 'Toronto', 'female', '$95,000','digital markter',  28, 79.0],
    [103, 'Chima', 'California', 'male','$120,000','data engineer', 33, 81.0],
    [104, 'Obi', 'Shanghai', 'male', '$85,000','product manager', 34, 80.0],
    [105, 'Stacey', 'Manchester', 'female','$97,000','ui/ux designer', 38, 68.0],
    [106, 'Ola', 'Cairo', '$98,000', 'female','software engineer', 31, 61.0],
    [107, 'Lyon', 'Osaka', '$96,000', 'male','project manager', 37, 84.0]
]

# Define column names
columns = ['', 'Name', 'City', 'Gender', 'Salary','Occupation', 'Age', 'Py-score']

# Create DataFrame
df = pd.DataFrame(data, columns=columns)

# Save as CSV file
df.to_csv('data.csv', index=False)

In [146]:
# import pandas as pd

# Read the CSV file
#df = pd.read_csv('data.csv')

# Display the first few rows to verify it loaded correctly
print(df.head())

# If the CSV has an unnamed index column, you can skip it with:
#df = pd.read_csv('data.csv', index_col=0)

# Or if you want to specify the first column as the index:
df = pd.read_csv('data.csv', index_col=0)

          Name        City  Gender    Salary       Occupation  Age  Py-score
0  101     Ada       Paris  female  $100,000   data scientist   41      88.0
1  102     Ann     Toronto  female   $95,000  digital markter   28      79.0
2  103   Chima  California    male  $120,000    data engineer   33      81.0
3  104     Obi    Shanghai    male   $85,000  product manager   34      80.0
4  105  Stacey  Manchester  female   $97,000   ui/ux designer   38      68.0

# Retrieving Labels and Data

In [147]:
'''
Now that you’ve created your DataFrame, you can start retrieving information from it. With pandas, you can perform the following actions:

Retrieve and modify row and column labels as sequences
Represent data as NumPy arrays
Check and adjust the data types
Analyze the size of DataFrame objects

'''
# Retrieve and modify row labels, 
# You can get the DataFrame’s row labels with .index 

df.index

Index([101, 102, 103, 104, 105, 106, 107], dtype='int64')

In [148]:
# Retrieve and modify the column labels
#You can get the DataFrame’s column labels with .columns:

df.columns

Index(['Name', 'City', 'Gender', 'Salary', 'Occupation', 'Age', 'Py-score'], dtype='object')

In [149]:
# You can also use this approach to modify the labels:
df.index = np.arange(10, 17)

df.index

df

      Name        City   Gender    Salary         Occupation  Age  Py-score
10     Ada       Paris   female  $100,000     data scientist   41      88.0
11     Ann     Toronto   female   $95,000    digital markter   28      79.0
12   Chima  California     male  $120,000      data engineer   33      81.0
13     Obi    Shanghai     male   $85,000    product manager   34      80.0
14  Stacey  Manchester   female   $97,000     ui/ux designer   38      68.0
15     Ola       Cairo  $98,000    female  software engineer   31      61.0
16    Lyon       Osaka  $96,000      male    project manager   37      84.0

In [150]:
'''
Data as NumPy Arrays
Sometimes you might want to extract data from a pandas DataFrame without its labels. 
To get a NumPy array with the unlabeled data, you can use either .to_numpy() or .values:

'''

df.to_numpy()

array([['Ada', 'Paris', 'female', '$100,000', 'data scientist', 41, 88.0],
       ['Ann', 'Toronto', 'female', '$95,000', 'digital markter', 28,
        79.0],
       ['Chima', 'California', 'male', '$120,000', 'data engineer', 33,
        81.0],
       ['Obi', 'Shanghai', 'male', '$85,000', 'product manager', 34,
        80.0],
       ['Stacey', 'Manchester', 'female', '$97,000', 'ui/ux designer',
        38, 68.0],
       ['Ola', 'Cairo', '$98,000', 'female', 'software engineer', 31,
        61.0],
       ['Lyon', 'Osaka', '$96,000', 'male', 'project manager', 37, 84.0]],
      dtype=object)

In [151]:
df.values

array([['Ada', 'Paris', 'female', '$100,000', 'data scientist', 41, 88.0],
       ['Ann', 'Toronto', 'female', '$95,000', 'digital markter', 28,
        79.0],
       ['Chima', 'California', 'male', '$120,000', 'data engineer', 33,
        81.0],
       ['Obi', 'Shanghai', 'male', '$85,000', 'product manager', 34,
        80.0],
       ['Stacey', 'Manchester', 'female', '$97,000', 'ui/ux designer',
        38, 68.0],
       ['Ola', 'Cairo', '$98,000', 'female', 'software engineer', 31,
        61.0],
       ['Lyon', 'Osaka', '$96,000', 'male', 'project manager', 37, 84.0]],
      dtype=object)

In [152]:
# TO get the data types for each column of a pandas DataFrame use .dtypes:
df.dtypes

Name           object
City           object
Gender         object
Salary         object
Occupation     object
Age             int64
Py-score      float64
dtype: object

In [153]:
# to modify the data type of one or more columns, then you can use .astype():
'''
The most important and only mandatory parameter of .astype() is dtype. 
It expects a data type or dictionary. If you pass a dictionary, 
then the keys are the column names and the values are your desired corresponding data types.
'''

df = df.astype(dtype={'Name':str, 'Age': np.int32, 'Py-score': np.float32})

In [154]:
df.values

array([['Ada', 'Paris', 'female', '$100,000', 'data scientist', 41, 88.0],
       ['Ann', 'Toronto', 'female', '$95,000', 'digital markter', 28,
        79.0],
       ['Chima', 'California', 'male', '$120,000', 'data engineer', 33,
        81.0],
       ['Obi', 'Shanghai', 'male', '$85,000', 'product manager', 34,
        80.0],
       ['Stacey', 'Manchester', 'female', '$97,000', 'ui/ux designer',
        38, 68.0],
       ['Ola', 'Cairo', '$98,000', 'female', 'software engineer', 31,
        61.0],
       ['Lyon', 'Osaka', '$96,000', 'male', 'project manager', 37, 84.0]],
      dtype=object)

In [155]:
# pandas DataFrame Size
'''
The attributes .ndim, .shape, and .size return the number of dimensions, 
number of data values across each dimension, and total number of data values, respectively:

'''
# To check the dimension of your dataframe .ndim
print("\nShow me the Dimension Of My DataFrame:\n",df.ndim)

# .shape attribute returns a tuple with the number of rows
print("\nShow Me The Number Of Attributes:\n",df.shape)

# To return an integer equal to the number of values in the DataFrame .df.size

print("\nShow Me total number of data values In My DataFrame:\n", df.size)

Show me the Dimension Of My DataFrame:
 2

Show Me The Number Of Attributes:
 (7, 7)

Show Me total number of data values In My DataFrame:
 49

In [156]:
# To check the amount of memory used by each column .memory_usage()

df.memory_usage()

Index         56
Name          56
City          56
Gender        56
Salary        56
Occupation    56
Age           28
Py-score      28
dtype: int64

# Accessing and Modifying Data

In [157]:
'''
In pandas you can access data using the four accessor in the following way:

1. .loc[] accepts the labels of rows and columns and returns Series or DataFrames. 
You can use it to get entire rows or columns, as well as their parts.

2. .iloc[] accepts the zero-based indices of rows and columns and returns Series or DataFrames. 
You can use it to get entire rows or columns, or their parts.

3. .at[] accepts the labels of rows and columns and returns a single data value.

4. .iat[] accepts the zero-based indices of rows and columns and returns a single data value.

Note: .loc[] and .iloc[] are particularly powerful. They support slicing and NumPy-style indexing. 
You can use them to access a column in the following way:

'''

'\nIn pandas you can access data using the four accessor in the following way:\n\n1. .loc[] accepts the labels of rows and columns and returns Series or DataFrames. \nYou can use it to get entire rows or columns, as well as their parts.\n\n2. .iloc[] accepts the zero-based indices of rows and columns and returns Series or DataFrames. \nYou can use it to get entire rows or columns, or their parts.\n\n3. .at[] accepts the labels of rows and columns and returns a single data value.\n\n4. .iat[] accepts the zero-based indices of rows and columns and returns a single data value.\n\nNote: .loc[] and .iloc[] are particularly powerful. They support slicing and NumPy-style indexing. \nYou can use them to access a column in the following way:\n\n'

In [158]:
# df.loc[:, 'Occupation'] returns the column city. The slice construct (:) in the row label place means that all the rows should be included.
df.loc[:, 'Occupation']

10       data scientist
11      digital markter
12        data engineer
13      product manager
14       ui/ux designer
15    software engineer
16      project manager
Name: Occupation, dtype: object

In [159]:
# df.iloc[:, 4] returns the same column because the zero-based index 1 refers to the four column, occupation.

df.iloc[:, 4]

10       data scientist
11      digital markter
12        data engineer
13      product manager
14       ui/ux designer
15    software engineer
16      project manager
Name: Occupation, dtype: object

In [160]:
df.iloc[1:6:2, 0]

11    Ann
13    Obi
15    Ola
Name: Name, dtype: object

In [161]:
df.iloc[1:6, [0,1]]

      Name        City
11     Ann     Toronto
12   Chima  California
13     Obi    Shanghai
14  Stacey  Manchester
15     Ola       Cairo