In [1]:
'''
Learning pandas sort methods is a great way to start with or practice doing basic data analysis using Python. 
Most commonly, data analysis is done with spreadsheets, SQL, or pandas. 
One of the great things about using pandas is that it can handle a large amount of data
and offers highly performant data manipulation capabilities.
'''

# let start by importing pandas

import pandas as pd
import numpy as np

column_subset = [
     "id",
     "make",
    "model",
    "year",
    "cylinders",
    "fuelType",
    "trany",
    "mpgData",
     "city08",
     "highway08"
 ]

df = pd.read_csv(
     "https://www.fueleconomy.gov/feg/epadata/vehicles.csv",
     usecols=column_subset,
    nrows=100
)

df.head()

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985
1,9,12,Regular,14,10,Ferrari,Testarossa,N,Manual 5-spd,1985
2,23,4,Regular,33,100,Dodge,Charger,Y,Manual 5-spd,1985
3,10,8,Regular,12,1000,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985
4,17,4,Premium,23,10000,Subaru,Legacy AWD Turbo,N,Manual 5-spd,1993

In [2]:
# To check our first 5 rows we use .head()

df.head()

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985
1,9,12,Regular,14,10,Ferrari,Testarossa,N,Manual 5-spd,1985
2,23,4,Regular,33,100,Dodge,Charger,Y,Manual 5-spd,1985
3,10,8,Regular,12,1000,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985
4,17,4,Premium,23,10000,Subaru,Legacy AWD Turbo,N,Manual 5-spd,1993

In [3]:
# To sort with .sort_values you must put the necessary argument or label= column name and axis whih is row
# in this exmaple we are sorting by the col name make and its axis

df.sort_values(by='make', axis = 0)

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985
18,17,6,Premium,22,10013,Audi,100,Y,Automatic 4-spd,1993
19,17,6,Premium,24,10014,Audi,100,N,Manual 5-spd,1993
20,14,8,Premium,20,10015,BMW,740i,N,Automatic 5-spd,1993
22,11,12,Regular,17,10017,BMW,750il,N,Automatic 4-spd,1993
...,...,...,...,...,...,...,...,...,...,...
13,18,4,Regular,26,10009,Volkswagen,Jetta III,N,Automatic 4-spd,1993
12,21,4,Regular,29,10008,Volkswagen,Golf III / GTI,Y,Manual 5-spd,1993
11,18,4,Regular,26,10007,Volkswagen,Golf III / GTI,N,Automatic 4-spd,1993
17,19,4,Regular,26,10012,Volvo,240,Y,Manual 5-spd,1993
16,18,4,Regular,23,10011,Volvo,240,Y,Automatic 4-spd,1993

In [4]:
'''
You use .sort_index() to sort a DataFrame by its row index or column labels. 
The difference from using .sort_values() is that you’re sorting the DataFrame based on its row index or column names, 
not by the values in these rows or columns:

'''

df.sort_index()

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985
1,9,12,Regular,14,10,Ferrari,Testarossa,N,Manual 5-spd,1985
2,23,4,Regular,33,100,Dodge,Charger,Y,Manual 5-spd,1985
3,10,8,Regular,12,1000,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985
4,17,4,Premium,23,10000,Subaru,Legacy AWD Turbo,N,Manual 5-spd,1993
...,...,...,...,...,...,...,...,...,...,...
95,17,6,Regular,25,10083,Pontiac,Grand Prix,Y,Automatic 3-spd,1993
96,17,6,Regular,27,10084,Pontiac,Grand Prix,N,Automatic 4-spd,1993
97,15,6,Regular,24,10085,Pontiac,Grand Prix,N,Automatic 4-spd,1993
98,15,6,Regular,24,10086,Pontiac,Grand Prix,N,Manual 5-spd,1993
99,9,8,Premium,13,10087,Rolls-Royce,Brooklands/Brklnds L,N,Automatic 4-spd,1993

# Sorting Your DataFrame on a Single Column

In [5]:
'''
To sort the DataFrame based on the values in a single column, you’ll use .sort_values(). By default, 
this will return a new DataFrame sorted in ascending order.
It does not modify the original DataFrame.

'''

# Sorting by a Column in Ascending Order by default

df.sort_values('fuelType')

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year
99,9,8,Premium,13,10087,Rolls-Royce,Brooklands/Brklnds L,N,Automatic 4-spd,1993
79,17,6,Premium,22,10069,Mazda,929,Y,Automatic 4-spd,1993
78,18,6,Premium,24,10068,Mazda,626,N,Manual 5-spd,1993
77,17,6,Premium,23,10067,Mazda,626,Y,Automatic 4-spd,1993
31,15,8,Premium,23,10025,Cadillac,Eldorado,N,Automatic 4-spd,1993
...,...,...,...,...,...,...,...,...,...,...
30,17,6,Regular,25,10024,Buick,Riviera,N,Automatic 4-spd,1993
29,17,6,Regular,26,10023,Buick,Regal,Y,Automatic 4-spd,1993
28,17,6,Regular,27,10022,Buick,Regal,N,Automatic 4-spd,1993
40,15,6,Regular,24,10033,Chevrolet,Lumina,N,Manual 5-spd,1993
49,18,6,Regular,26,10041,Dodge,Dynasty,Y,Automatic 4-spd,1993

In [6]:
''' Changing the Sort Order 
 If you want the DataFrame sorted in descending order, then you can pass False to this parameter:

'''

df.sort_values('fuelType', ascending = False)

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985
47,9,8,Regular,11,1004,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985
73,18,6,Regular,27,10063,Mercury,Sable,N,Automatic 4-spd,1993
72,15,8,Regular,22,10062,Mercury,Cougar,Y,Automatic 4-spd,1993
71,17,6,Regular,24,10061,Mercury,Cougar,N,Automatic 4-spd,1993
...,...,...,...,...,...,...,...,...,...,...
70,16,8,Premium,22,10060,Lexus,LS 400,Y,Automatic 4-spd,1993
46,18,6,Premium,24,10039,Nissan,Maxima,Y,Manual 5-spd,1993
21,14,8,Premium,20,10016,BMW,740il,N,Automatic 5-spd,1993
77,17,6,Premium,23,10067,Mazda,626,Y,Automatic 4-spd,1993
99,9,8,Premium,13,10087,Rolls-Royce,Brooklands/Brklnds L,N,Automatic 4-spd,1993

# Choosing a Sorting Algorithm

In [9]:
'''
pandas allows you to choose different sorting algorithms to use with both .sort_values() and .sort_index(). 
The available algorithms are quicksort, mergesort, and heapsort. 

The algorithm used by default when sorting on a single column is quicksort. 
To change this to a stable sorting algorithm, use mergesort. 
You can do that with the kind parameter in .sort_values() or .sort_index(), like this:

'''

df.sort_values(by="city08", ascending = False, kind = "mergesort")
df

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985
1,9,12,Regular,14,10,Ferrari,Testarossa,N,Manual 5-spd,1985
2,23,4,Regular,33,100,Dodge,Charger,Y,Manual 5-spd,1985
3,10,8,Regular,12,1000,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985
4,17,4,Premium,23,10000,Subaru,Legacy AWD Turbo,N,Manual 5-spd,1993
...,...,...,...,...,...,...,...,...,...,...
95,17,6,Regular,25,10083,Pontiac,Grand Prix,Y,Automatic 3-spd,1993
96,17,6,Regular,27,10084,Pontiac,Grand Prix,N,Automatic 4-spd,1993
97,15,6,Regular,24,10085,Pontiac,Grand Prix,N,Automatic 4-spd,1993
98,15,6,Regular,24,10086,Pontiac,Grand Prix,N,Manual 5-spd,1993
99,9,8,Premium,13,10087,Rolls-Royce,Brooklands/Brklnds L,N,Automatic 4-spd,1993

# Sorting Your DataFrame on Multiple Columns

In [10]:
'''

imagaine you have a dataset of customer name and your performing analysis on it.
It would make sense to sort by last name and then first name, 
so that people with the same last name are arranged alphabetically according to their first names.

in our dataframe we have details about cars the MPG in city conditions is an important factor that could determine a car’s desirability.
In addition to the MPG in city conditions, you may also want to look at MPG for highway conditions.
To sort by two keys, you can pass a list of column names to by:

'''

df.sort_values(["city08", "highway08"]) [["city08", "highway08"]]

    city08  highway08
80       9         10
47       9         11
99       9         13
1        9         14
58      10         11
..     ...        ...
9       23         30
10      23         30
8       23         31
76      23         31
2       23         33

[100 rows x 2 columns]

In [13]:
# Sorting by Multiple Columns in Ascending Order

'''
To sort the DataFrame on multiple columns, you must provide a list of column names.
For example, to sort by make and model, you should create the following list and 
then pass it to .sort_values():

from the example below:
DataFrame is sorted in ascending order by make. If there are two or more identical makes,
then it’s sorted by model. The order in which the column names are specified in your list corresponds to how your DataFrame will be sorted.

'''

df.sort_values(by = ["make" , "model"]) [["make", "model"]]

          make               model
0   Alfa Romeo  Spider Veloce 2000
18        Audi                 100
19        Audi                 100
20         BMW                740i
21         BMW               740il
..         ...                 ...
12  Volkswagen      Golf III / GTI
13  Volkswagen           Jetta III
15  Volkswagen           Jetta III
16       Volvo                 240
17       Volvo                 240

[100 rows x 2 columns]

In [15]:
# Changing the Column Sort Order
# Since you’re sorting using multiple columns, you can specify the order by which your columns get sorted.

df.sort_values(by = ["model" , "make"]) [["make", "model"]]

             make        model
18           Audi          100
19           Audi          100
16          Volvo          240
17          Volvo          240
75          Mazda          626
..            ...          ...
62           Ford  Thunderbird
63           Ford  Thunderbird
88     Oldsmobile     Toronado
42  CX Automotive        XM v6
43  CX Automotive       XM v6a

[100 rows x 2 columns]

In [18]:
'''
Sorting by Multiple Columns in Descending Order
Up to this point, you’ve sorted only in ascending order on multiple columns. 
In the next example, you’ll sort in descending order based on the make and model columns. 
To sort in descending order, set ascending to False:

'''

df.sort_values(by = ["make" , "model"], ascending = False) [["make", "model"]]

          make               model
16       Volvo                 240
17       Volvo                 240
13  Volkswagen           Jetta III
15  Volkswagen           Jetta III
11  Volkswagen      Golf III / GTI
..         ...                 ...
21         BMW               740il
20         BMW                740i
18        Audi                 100
19        Audi                 100
0   Alfa Romeo  Spider Veloce 2000

[100 rows x 2 columns]

In [25]:
# Sorting by Multiple Columns With Different Sort Orders

'''
If you want to sort some columns in ascending order and some columns in descending order, 
then you can pass a list of Booleans to ascending.

In this example, you sort your DataFrame by the make, model, and city08 columns,
with the first two columns sorted in ascending order and city08 sorted in descending order. 
To do so, you pass a list of column names to by and a list of Booleans to ascending:

This is helpful because it groups the cars in a categorical order and shows the highest MPG cars first.
'''

df.sort_values(by = ["make" , "model", "city08"], ascending =[ True, True, False])[["make", "model", "city08"]]

          make               model  city08
0   Alfa Romeo  Spider Veloce 2000      19
18        Audi                 100      17
19        Audi                 100      17
20         BMW                740i      14
21         BMW               740il      14
..         ...                 ...     ...
11  Volkswagen      Golf III / GTI      18
15  Volkswagen           Jetta III      20
13  Volkswagen           Jetta III      18
17       Volvo                 240      19
16       Volvo                 240      18

[100 rows x 3 columns]

# Sorting Your DataFrame on Its Index

In [27]:
'''
Before sorting on the index, it’s a good idea to know what an index represents. 
A DataFrame has an .index property, which by default is a numerical representation of its rows’ locations. 
You can think of the index as the row numbers. It helps in quick row lookup and identification.

Sorting by Index in Ascending Order
You can sort a DataFrame based on its row index with .sort_index(). 
Sorting by column values like you did in the previous examples reorders the rows in your DataFrame, 
so the index becomes disorganized. 
This can also happen when you filter a DataFrame or when you drop or add rows.

'''

sorted_df = df.sort_values(by=["make", "model"])
sorted_df

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985
18,17,6,Premium,22,10013,Audi,100,Y,Automatic 4-spd,1993
19,17,6,Premium,24,10014,Audi,100,N,Manual 5-spd,1993
20,14,8,Premium,20,10015,BMW,740i,N,Automatic 5-spd,1993
21,14,8,Premium,20,10016,BMW,740il,N,Automatic 5-spd,1993
...,...,...,...,...,...,...,...,...,...,...
12,21,4,Regular,29,10008,Volkswagen,Golf III / GTI,Y,Manual 5-spd,1993
13,18,4,Regular,26,10009,Volkswagen,Jetta III,N,Automatic 4-spd,1993
15,20,4,Regular,28,10010,Volkswagen,Jetta III,N,Manual 5-spd,1993
16,18,4,Regular,23,10011,Volvo,240,Y,Automatic 4-spd,1993
17,19,4,Regular,26,10012,Volvo,240,Y,Manual 5-spd,1993

In [28]:
 '''
 from the result above this cell Notice how the row index is in no particular order. 
 To get your new DataFrame back to the original order, you can use .sort_index():

 Sorting on the index has no impact on the data itself as the values are unchanged.
 '''

sorted_df.sort_index()

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985
1,9,12,Regular,14,10,Ferrari,Testarossa,N,Manual 5-spd,1985
2,23,4,Regular,33,100,Dodge,Charger,Y,Manual 5-spd,1985
3,10,8,Regular,12,1000,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985
4,17,4,Premium,23,10000,Subaru,Legacy AWD Turbo,N,Manual 5-spd,1993
...,...,...,...,...,...,...,...,...,...,...
95,17,6,Regular,25,10083,Pontiac,Grand Prix,Y,Automatic 3-spd,1993
96,17,6,Regular,27,10084,Pontiac,Grand Prix,N,Automatic 4-spd,1993
97,15,6,Regular,24,10085,Pontiac,Grand Prix,N,Automatic 4-spd,1993
98,15,6,Regular,24,10086,Pontiac,Grand Prix,N,Manual 5-spd,1993
99,9,8,Premium,13,10087,Rolls-Royce,Brooklands/Brklnds L,N,Automatic 4-spd,1993

In [34]:
'''
 If you want to set a custom index using the make and model columns, 
 then you can pass a list to .set_index():

This replace the default integer-based row index with two axis labels(make and mode). 
This is considered a MultiIndex or a hierarchical index. 
Your DataFrame is now indexed by more than one key, which you can sort on with .sort_index():

'''

assign_index_df = df.set_index(['make','model'])
assign_index_df

                                  city08  cylinders fuelType  highway08  \
make        model
Alfa Romeo  Spider Veloce 2000        19          4  Regular         25
Ferrari     Testarossa                 9         12  Regular         14
Dodge       Charger                   23          4  Regular         33
            B150/B250 Wagon 2WD       10          8  Regular         12
Subaru      Legacy AWD Turbo          17          4  Premium         23
...                                  ...        ...      ...        ...
Pontiac     Grand Prix                17          6  Regular         25
            Grand Prix                17          6  Regular         27
            Grand Prix                15          6  Regular         24
            Grand Prix                15          6  Regular         24
Rolls-Royce Brooklands/Brklnds L       9          8  Premium         13

                                     id mpgData            trany  year
make        model
Alfa Romeo  Spider Veloce 2000        1       Y     Manual 5-spd  1985
Ferrari     Testarossa               10       N     Manual 5-spd  1985
Dodge       Charger                 100       Y     Manual 5-spd  1985
            B150/B250 Wagon 2WD    1000       N  Automatic 3-spd  1985
Subaru      Legacy AWD Turbo      10000       N     Manual 5-spd  1993
...                                 ...     ...              ...   ...
Pontiac     Grand Prix            10083       Y  Automatic 3-spd  1993
            Grand Prix            10084       N  Automatic 4-spd  1993
            Grand Prix            10085       N  Automatic 4-spd  1993
            Grand Prix            10086       N     Manual 5-spd  1993
Rolls-Royce Brooklands/Brklnds L  10087       N  Automatic 4-spd  1993

[100 rows x 8 columns]

In [35]:
# Sorting by Index in Descending Order

'''
in this example you will sort your DataFrame by its index in descending order. 
Remember from sorting your DataFrame with .sort_values() 
that you can reverse the sort order by setting ascending to False. 
This parameter also works with .sort_index(), so you can sort your DataFrame in reverse order like this:

'''
assign_index_df.sort_index(ascending = False)

                               city08  cylinders fuelType  highway08     id  \
make       model
Volvo      240                     18          4  Regular         23  10011
           240                     19          4  Regular         26  10012
Volkswagen Jetta III               18          4  Regular         26  10009
           Jetta III               20          4  Regular         28  10010
           Golf III / GTI          18          4  Regular         26  10007
...                               ...        ...      ...        ...    ...
BMW        740il                   14          8  Premium         20  10016
           740i                    14          8  Premium         20  10015
Audi       100                     17          6  Premium         22  10013
           100                     17          6  Premium         24  10014
Alfa Romeo Spider Veloce 2000      19          4  Regular         25      1

                              mpgData            trany  year
make       model
Volvo      240                      Y  Automatic 4-spd  1993
           240                      Y     Manual 5-spd  1993
Volkswagen Jetta III                N  Automatic 4-spd  1993
           Jetta III                N     Manual 5-spd  1993
           Golf III / GTI           N  Automatic 4-spd  1993
...                               ...              ...   ...
BMW        740il                    N  Automatic 5-spd  1993
           740i                     N  Automatic 5-spd  1993
Audi       100                      Y  Automatic 4-spd  1993
           100                      N     Manual 5-spd  1993
Alfa Romeo Spider Veloce 2000       Y     Manual 5-spd  1985

[100 rows x 8 columns]

# Sorting the Columns of Your DataFrame

In [36]:
'''
You can also use the column labels of your DataFrame to sort row values.
Using .sort_index() with the optional parameter axis set to 1 will sort the DataFrame by the column labels. 
The sorting algorithm is applied to the axis labels instead of to the actual data.
'''

# Working With the DataFrame axis
'''
When you use .sort_index() without passing any explicit arguments, it uses axis=0 as a default argument. 
The axis of a DataFrame refers to either the index (axis=0) or the columns (axis=1).

'''

# Using Column Labels to Sort
'''
You can also use the column labels of a DataFrame as the sorting key for .sort_index(). 
Setting axis to 1 sorts the columns of your DataFrame based on the column labels:

'''

df.sort_index(axis=1)

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985
1,9,12,Regular,14,10,Ferrari,Testarossa,N,Manual 5-spd,1985
2,23,4,Regular,33,100,Dodge,Charger,Y,Manual 5-spd,1985
3,10,8,Regular,12,1000,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985
4,17,4,Premium,23,10000,Subaru,Legacy AWD Turbo,N,Manual 5-spd,1993
...,...,...,...,...,...,...,...,...,...,...
95,17,6,Regular,25,10083,Pontiac,Grand Prix,Y,Automatic 3-spd,1993
96,17,6,Regular,27,10084,Pontiac,Grand Prix,N,Automatic 4-spd,1993
97,15,6,Regular,24,10085,Pontiac,Grand Prix,N,Automatic 4-spd,1993
98,15,6,Regular,24,10086,Pontiac,Grand Prix,N,Manual 5-spd,1993
99,9,8,Premium,13,10087,Rolls-Royce,Brooklands/Brklnds L,N,Automatic 4-spd,1993

In [41]:
'''
from the above result we can see that the columns(column name) of your DataFrame are sorted from left to right in ascending alphabetical order.
If you want to sort the columns in descending order(making year column come first in our dataframe), 
then you can use ascending=False:

'''

df.sort_index(ascending=False , axis=1)

,year,trany,mpgData,model,make,id,highway08,fuelType,cylinders,city08
0,1985,Manual 5-spd,Y,Spider Veloce 2000,Alfa Romeo,1,25,Regular,4,19
1,1985,Manual 5-spd,N,Testarossa,Ferrari,10,14,Regular,12,9
2,1985,Manual 5-spd,Y,Charger,Dodge,100,33,Regular,4,23
3,1985,Automatic 3-spd,N,B150/B250 Wagon 2WD,Dodge,1000,12,Regular,8,10
4,1993,Manual 5-spd,N,Legacy AWD Turbo,Subaru,10000,23,Premium,4,17
...,...,...,...,...,...,...,...,...,...,...
95,1993,Automatic 3-spd,Y,Grand Prix,Pontiac,10083,25,Regular,6,17
96,1993,Automatic 4-spd,N,Grand Prix,Pontiac,10084,27,Regular,6,17
97,1993,Automatic 4-spd,N,Grand Prix,Pontiac,10085,24,Regular,6,15
98,1993,Manual 5-spd,N,Grand Prix,Pontiac,10086,24,Regular,6,15
99,1993,Automatic 4-spd,N,Brooklands/Brklnds L,Rolls-Royce,10087,13,Premium,8,9

# Working With Missing Data When Sorting in Pandas
### 
In real-world secnarios data has many imperfections. While pandas has several methods you can use to clean your data before sorting, 
sometimes it’s nice to see which data is missing while you’re sorting. 
You can do that with the na_position parameter.

In this lesson we are going to create a dataset that have NaN to demonstrate working with missing Data 
The following piece of code creates a new column based on the existing mpgData column, 
mapping True where mpgData equals Y and NaN where it doesn’t:

In [43]:

df["mpgData_"] = df["mpgData"].map({"Y": True})
df

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year,mpgData_
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985,True
1,9,12,Regular,14,10,Ferrari,Testarossa,N,Manual 5-spd,1985,NaN
2,23,4,Regular,33,100,Dodge,Charger,Y,Manual 5-spd,1985,True
3,10,8,Regular,12,1000,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985,NaN
4,17,4,Premium,23,10000,Subaru,Legacy AWD Turbo,N,Manual 5-spd,1993,NaN
...,...,...,...,...,...,...,...,...,...,...,...
95,17,6,Regular,25,10083,Pontiac,Grand Prix,Y,Automatic 3-spd,1993,True
96,17,6,Regular,27,10084,Pontiac,Grand Prix,N,Automatic 4-spd,1993,NaN
97,15,6,Regular,24,10085,Pontiac,Grand Prix,N,Automatic 4-spd,1993,NaN
98,15,6,Regular,24,10086,Pontiac,Grand Prix,N,Manual 5-spd,1993,NaN
99,9,8,Premium,13,10087,Rolls-Royce,Brooklands/Brklnds L,N,Automatic 4-spd,1993,NaN

In [44]:
# Understanding the na_position Parameter in .sort_values()

'''
.sort_values() accepts a parameter named NaN position, which helps to organize missing data in the column you’re sorting on. 
If you sort on a column with missing data, then the rows with the missing values will appear at the end of your DataFrame. 
This happens regardless of whether you’re sorting in ascending or descending order.

'''
df.sort_values(by="mpgData_")

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year,mpgData_
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985,True
55,18,6,Regular,26,10047,Dodge,Spirit,Y,Automatic 4-spd,1993,True
56,18,6,Regular,27,10048,Ford,Taurus,Y,Automatic 4-spd,1993,True
57,16,6,Premium,24,10049,Ford,Taurus SHO,Y,Manual 5-spd,1993,True
59,17,6,Regular,25,10050,Ford,Taurus,Y,Automatic 4-spd,1993,True
...,...,...,...,...,...,...,...,...,...,...,...
94,18,6,Regular,26,10082,Plymouth,Acclaim,N,Automatic 4-spd,1993,NaN
96,17,6,Regular,27,10084,Pontiac,Grand Prix,N,Automatic 4-spd,1993,NaN
97,15,6,Regular,24,10085,Pontiac,Grand Prix,N,Automatic 4-spd,1993,NaN
98,15,6,Regular,24,10086,Pontiac,Grand Prix,N,Manual 5-spd,1993,NaN
99,9,8,Premium,13,10087,Rolls-Royce,Brooklands/Brklnds L,N,Automatic 4-spd,1993,NaN

In [47]:
'''
To change the look and have the missing data appear first in your DataFrame, you can set "na_position" to first. 
The na_position parameter only accepts the values last, which is the default, and first.
Here’s how to use na_postion in .sort_values():

'''

df.sort_values(by="mpgData_", na_position="first")

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year,mpgData_
1,9,12,Regular,14,10,Ferrari,Testarossa,N,Manual 5-spd,1985,NaN
3,10,8,Regular,12,1000,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985,NaN
4,17,4,Premium,23,10000,Subaru,Legacy AWD Turbo,N,Manual 5-spd,1993,NaN
5,21,4,Regular,24,10001,Subaru,Loyale,N,Automatic 3-spd,1993,NaN
11,18,4,Regular,26,10007,Volkswagen,Golf III / GTI,N,Automatic 4-spd,1993,NaN
...,...,...,...,...,...,...,...,...,...,...,...
32,15,8,Premium,23,10026,Cadillac,Eldorado,Y,Automatic 4-spd,1993,True
33,15,8,Premium,23,10027,Cadillac,Seville,Y,Automatic 4-spd,1993,True
37,17,6,Regular,25,10030,Chevrolet,Lumina,Y,Automatic 3-spd,1993,True
85,17,6,Regular,27,10074,Oldsmobile,Cutlass Supreme,Y,Automatic 4-spd,1993,True
95,17,6,Regular,25,10083,Pontiac,Grand Prix,Y,Automatic 3-spd,1993,True

# Using Sort Methods to Modify Your DataFrame

####
In all the examples you’ve seen so far, both .sort_values() and .sort_index() have returned DataFrame objects when you called those methods. That’s because sorting in pandas doesn’t work in place by default. In general, this is the most common and preferred way to analyze your data with pandas since it creates a new DataFrame instead of modifying the original. This allows you to preserve the state of the data from when you read it from your file.

However, you can modify the original DataFrame directly by specifying the optional parameter inplace with the value of True.

In [49]:
#Using .sort_values() In Place

df.sort_values(by="city08", inplace=True)
df

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year,mpgData_
1,9,12,Regular,14,10,Ferrari,Testarossa,N,Manual 5-spd,1985,NaN
47,9,8,Regular,11,1004,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985,NaN
99,9,8,Premium,13,10087,Rolls-Royce,Brooklands/Brklnds L,N,Automatic 4-spd,1993,NaN
80,9,8,Regular,10,1007,Dodge,B350 Wagon 2WD,N,Automatic 3-spd,1985,NaN
58,10,8,Regular,11,1005,Dodge,B350 Wagon 2WD,N,Automatic 3-spd,1985,NaN
...,...,...,...,...,...,...,...,...,...,...,...
9,23,4,Regular,30,10005,Toyota,Corolla,Y,Automatic 4-spd,1993,True
2,23,4,Regular,33,100,Dodge,Charger,Y,Manual 5-spd,1985,True
8,23,4,Regular,31,10004,Toyota,Corolla,Y,Manual 5-spd,1993,True
10,23,4,Regular,30,10006,Toyota,Corolla,Y,Manual 5-spd,1993,True
76,23,4,Regular,31,10066,Mazda,626,Y,Manual 5-spd,1993,True

In [51]:
# Using .sort_index() In Place

'''
This example illustrates that inplace also works with .sort_index().
Since the index was created in ascending order when you read your file into a DataFrame, 
you can modify your df object again to get it back to its initial order. 
Use .sort_index() with inplace set to True to modify the DataFrame:

'''

df.sort_index(inplace=False)

,city08,cylinders,fuelType,highway08,id,make,model,mpgData,trany,year,mpgData_
0,19,4,Regular,25,1,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,1985,True
1,9,12,Regular,14,10,Ferrari,Testarossa,N,Manual 5-spd,1985,NaN
2,23,4,Regular,33,100,Dodge,Charger,Y,Manual 5-spd,1985,True
3,10,8,Regular,12,1000,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,1985,NaN
4,17,4,Premium,23,10000,Subaru,Legacy AWD Turbo,N,Manual 5-spd,1993,NaN
...,...,...,...,...,...,...,...,...,...,...,...
95,17,6,Regular,25,10083,Pontiac,Grand Prix,Y,Automatic 3-spd,1993,True
96,17,6,Regular,27,10084,Pontiac,Grand Prix,N,Automatic 4-spd,1993,NaN
97,15,6,Regular,24,10085,Pontiac,Grand Prix,N,Automatic 4-spd,1993,NaN
98,15,6,Regular,24,10086,Pontiac,Grand Prix,N,Manual 5-spd,1993,NaN
99,9,8,Premium,13,10087,Rolls-Royce,Brooklands/Brklnds L,N,Automatic 4-spd,1993,NaN